# ==============================================================================
# Merged Lakeflow Source: bluesky
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime
from decimal import Decimal
from typing import (
    Annotated,
    Any,
    Iterator,
    Literal,
    Mapping,
    Sequence,
)
import json
import re

from contextlib import contextmanager
from jetstream_lakehouse import errors as library_errors # pylint: disable=import-error
from jetstream_lakehouse.archive import segment_events # pylint: disable=import-error
from jetstream_lakehouse.models import Event # pylint: disable=import-error
from jetstream_lakehouse.transport import Transport # pylint: disable=import-error
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StringConstraints,
    field_validator,
    model_validator,
)
from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
from urllib.parse import urlsplit
import base64
import hashlib


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/bluesky/errors.py
    ########################################################

    class JetstreamError(RuntimeError):
        """Base exception for failed Jetstream refreshes.

        Notes
        -----
        A failed refresh must not commit its candidate offset.
        """


    class ProtocolError(JetstreamError):
        """An unsupported or corrupt server response was encountered.

        Notes
        -----
        Raised when a response violates the supported Jetstream archive protocol.
        """


    class CursorTooOld(JetstreamError):
        """The requested archive range is no longer available.

        Notes
        -----
        The connector does not skip data or silently reset an expired cursor.
        """


    class ArchiveChanged(JetstreamError):
        """The planned archive generation is unavailable for replay.

        Notes
        -----
        Retrying cannot safely replace the recorded plan with a new archive generation.
        """


    class RefreshTimeout(JetstreamError):
        """The bounded request or refresh time budget was exhausted.

        Notes
        -----
        Retain the previous checkpoint and retry in a later refresh.
        """


    ########################################################
    # src/databricks/labs/community_connector/sources/bluesky/options.py
    ########################################################

    MAX_SEQ = (1 << 63) - 1
    EventKind = Literal["commit", "identity", "account", "sync"]
    EVENT_KINDS: tuple[EventKind, ...] = ("commit", "identity", "account", "sync")
    Collection = Annotated[
        str,
        StringConstraints(
            pattern=r"^[a-zA-Z][a-zA-Z0-9-]*(?:\.[a-zA-Z][a-zA-Z0-9-]*)+\.(?:[a-zA-Z][a-zA-Z0-9]*|\*)$"
        ),
    ]
    Did = Annotated[str, StringConstraints(pattern=r"^did:[a-z0-9]+:[A-Za-z0-9._:%-]+$")]
    TABLE_OPTIONS = {
        "starting_cursor",
        "collections",
        "kinds",
        "dids",
        "max_events_per_refresh",
        "request_timeout_seconds",
        "refresh_timeout_seconds",
        "max_retries",
        "include_raw_payload",
    }
    CONNECTION_OPTIONS = {"endpoint", "api_key"}
    FRAMEWORK_OPTIONS = {
        "tableName",
        "table_name",
        "source",
        "connection_name",
        "databricks.connection",
        "externalOptionsAllowList",
        "external_options_allowlist",
        "operation",
        "sourceName",
        "auth_type",
        "tableNameList",
        "tableConfigs",
        "isDeleteFlow",
    }


    class Options(BaseModel):
        """Validated settings used throughout one connector read.

        Attributes
        ----------
        endpoint : str
            HTTPS origin hosting the Jetstream archive API.
        api_key : str
            Optional bearer token for archive access. Hidden from the model repr.
        starting_cursor : int
            Exclusive sequence cursor used when no checkpoint is available.
        collections : tuple[str, ...]
            Commit collections or namespace wildcards selected for the read.
        kinds : tuple[EventKind, ...]
            Jetstream event kinds selected for the read.
        dids : tuple[str, ...]
            Repository DIDs selected for the read.
        max_events_per_refresh : int
            Maximum sequence span planned for one refresh.
        request_timeout_seconds : int
            Per-request timeout limit.
        refresh_timeout_seconds : int
            Overall planning and reading time limit.
        max_retries : int
            Number of retries allowed for transient request failures.
        include_raw_payload : bool
            Whether decoded rows retain the encoded event payload.

        Notes
        -----
        Use :meth:`parse` to construct settings from Lakeflow or Dynaconf mappings.
        """

        model_config = ConfigDict(frozen=True, extra="forbid", hide_input_in_errors=True)

        endpoint: str = "https://jetstream.us-east.bsky.network"
        api_key: str = Field(default="", repr=False, exclude=True)
        starting_cursor: int = Field(default=0, ge=0, le=MAX_SEQ)
        collections: tuple[Collection, ...] = Field(default=(), max_length=100)
        kinds: tuple[EventKind, ...] = Field(
            default=tuple(sorted(EVENT_KINDS)), min_length=1, max_length=4
        )
        dids: tuple[Did, ...] = Field(default=(), max_length=10000)
        max_events_per_refresh: int = Field(default=10000, ge=1, le=100000)
        request_timeout_seconds: int = Field(default=20, ge=1, le=120)
        refresh_timeout_seconds: int = Field(default=120, ge=1, le=900)
        max_retries: int = Field(default=3, ge=0, le=8)
        include_raw_payload: bool = True

        @field_validator("endpoint", mode="before")
        @classmethod
        def validate_endpoint(cls, value: Any) -> str:
            if not isinstance(value, str):
                raise ValueError("endpoint must be an HTTPS origin")
            endpoint = value.rstrip("/")
            url = urlsplit(endpoint)
            if (  # pylint: disable=too-many-boolean-expressions
                url.scheme != "https"
                or not url.hostname
                or url.username
                or url.password
                or url.query
                or url.fragment
                or url.path
            ):
                raise ValueError("endpoint must be an HTTPS origin without credentials, path or query")
            return endpoint

        @field_validator("api_key")
        @classmethod
        def validate_api_key(cls, value: str) -> str:
            if any(char.isspace() for char in value):
                raise ValueError("api_key must be a raw bearer token without whitespace")
            return value

        @field_validator(
            "starting_cursor",
            "max_events_per_refresh",
            "request_timeout_seconds",
            "refresh_timeout_seconds",
            "max_retries",
            mode="before",
        )
        @classmethod
        def validate_decimal(cls, value: Any) -> Any:
            if isinstance(value, bool) or not re.fullmatch(r"[0-9]+", str(value)):
                raise ValueError("must be an unsigned decimal integer")
            return value

        @field_validator("collections", "kinds", "dids", mode="before")
        @classmethod
        def parse_selection(cls, value: Any) -> tuple[str, ...]:
            if not isinstance(value, str):
                raise ValueError("must be a comma-separated string")
            if not value.strip():
                return ()
            return tuple(sorted(set(part.strip() for part in value.split(","))))

        @field_validator("include_raw_payload", mode="before")
        @classmethod
        def validate_raw_payload(cls, value: Any) -> bool:
            if value not in ("true", "false"):
                raise ValueError("include_raw_payload must be 'true' or 'false'")
            return value == "true"

        @model_validator(mode="after")
        def validate_scope(self) -> "Options":
            if self.collections and "commit" not in self.kinds:
                raise ValueError("collections can only be used when kinds includes commit")
            return self

        @classmethod
        def parse(cls, connection: Mapping[str, Any], table: Mapping[str, Any]) -> "Options":
            # Spark lowercases keys in CaseInsensitiveDict, including framework options.
            connection = {key.lower(): value for key, value in connection.items()}
            table = {key.lower(): value for key, value in table.items()}
            unknown = (set(connection) | set(table)) - (
                TABLE_OPTIONS | CONNECTION_OPTIONS | {key.lower() for key in FRAMEWORK_OPTIONS}
            )
            if unknown:
                raise ValueError("Unsupported connector option names")
            if set(table) & CONNECTION_OPTIONS:
                # Framework forwards merged connection options to read methods.
                if any(table[k] != connection.get(k) for k in set(table) & CONNECTION_OPTIONS):
                    raise ValueError("Connection options cannot be overridden per table")
            values = {
                key: value
                for key, value in {**connection, **table}.items()
                if key in TABLE_OPTIONS | CONNECTION_OPTIONS
            }
            return cls.model_validate(values)

        def fingerprint(self) -> str:
            # Credentials and operational limits can rotate without invalidating a checkpoint.
            scope = [
                self.endpoint,
                self.starting_cursor,
                self.collections,
                self.kinds,
                self.dids,
                self.include_raw_payload,
            ]
            return hashlib.sha256(json.dumps(scope).encode()).hexdigest()

        def matches(self, event: Mapping[str, Any]) -> bool:
            if event["kind"] not in self.kinds:
                return False
            if self.dids and event["did"] not in self.dids:
                return False
            if event["kind"] != "commit" or not self.collections:
                return True
            collection = event["collection"]
            return any(
                collection == c or (c.endswith(".*") and collection.startswith(c[:-1]))
                for c in self.collections
            )

        def to_options_dict(self) -> dict[str, str]:
            """Return string options for the Lakeflow base interface boundary."""
            return {
                "endpoint": self.endpoint,
                "api_key": self.api_key,
                "starting_cursor": str(self.starting_cursor),
                "collections": ",".join(self.collections),
                "kinds": ",".join(self.kinds),
                "dids": ",".join(self.dids),
                "max_events_per_refresh": str(self.max_events_per_refresh),
                "request_timeout_seconds": str(self.request_timeout_seconds),
                "refresh_timeout_seconds": str(self.refresh_timeout_seconds),
                "max_retries": str(self.max_retries),
                "include_raw_payload": str(self.include_raw_payload).lower(),
            }

        def with_table_options(self, table: Mapping[str, Any]) -> "Options":
            """Return a validated config with table values layered over this config."""
            return type(self).parse(self.to_options_dict(), table)


    ########################################################
    # src/databricks/labs/community_connector/sources/bluesky/jetstream_lakeflow_adapter.py
    ########################################################

    def lakeflow_row(event: Event, include_raw_payload: bool) -> dict:
        """Restore Lakeflow's base64 and non-null JSON values from a library event."""
        row = event.as_dict()
        raw = row.pop("raw_payload_base64")
        # Spark's BinaryType parser decodes base64; the existing connector returns text.
        row["raw_payload"] = raw if raw is not None else "" if include_raw_payload else None
        # Lakeflow's event_payload column is non-nullable; empty CBOR is JSON null.
        row["event_payload"] = row["event_payload"] or "null"
        return row


    @contextmanager
    def translated_errors() -> Iterator[None]:
        """Keep the connector's exception types at the package boundary."""
        try:
            yield
        except library_errors.ArchiveChanged as exc:
            raise ArchiveChanged(str(exc)) from None
        except library_errors.CursorTooOld as exc:
            raise CursorTooOld(str(exc)) from None
        except library_errors.RefreshTimeout as exc:
            raise RefreshTimeout(str(exc)) from None
        except library_errors.ProtocolError as exc:
            raise ProtocolError(str(exc)) from None
        except library_errors.JetstreamError as exc:
            raise JetstreamError(str(exc)) from None


    @contextmanager
    def pinned_transport(options: Options) -> Iterator[Transport]:
        """Open the package transport while retaining the recorded archive plan.

        Notes
        -----
        Version 0.1.0 has no public two-phase archive API. Its private transport
        and decoder preserve the pinned segment checksums in Lakeflow offsets;
        the exact dependency pin and connector tests guard this temporary bridge.
        """
        with translated_errors(), Transport(options) as transport:
            yield transport


    def pinned_rows(
        transport: Transport,
        entry: Mapping[str, Any],
        after: int,
        through: int,
        include_raw_payload: bool,
    ) -> Iterator[dict[str, Any]]:
        """Decode one recorded segment without replanning it."""
        for row in segment_events(transport, entry, after, through, include_raw_payload):
            yield lakeflow_row(Event.from_archive(row), include_raw_payload)


    ########################################################
    # src/databricks/labs/community_connector/sources/bluesky/bluesky.py
    ########################################################

    MAX_PLAN_BYTES = 2 * 1024 * 1024
    MAX_BATCH_BYTES = 64 * 1024 * 1024
    # Connector safety cap for paginated plans, not a Jetstream API limit.
    MAX_PLAN_PAGES = 100


    class ArchiveValidator:
        """Validate untrusted checkpoint values and snapshot planner descriptors.

        Notes
        -----
        Validation failures raise :class:`ProtocolError` so malformed or unsupported
        planner data cannot produce a checkpoint that Lakeflow might commit.
        """

        @staticmethod
        def sequence(value: Any, name: str) -> int:
            """Validate an archive sequence supplied by a checkpoint or planner.

            Parameters
            ----------
            value : Any
                Value to check. Only a Python integer is accepted.
            name : str
                Field name used in a sanitized error message.

            Returns
            -------
            int
                Non-negative sequence within the connector's supported range.

            Raises
            ------
            ProtocolError
                The value is not an integer or is outside the supported range.

            Notes
            -----
            A boolean is rejected even though it is a subclass of ``int``.
            """
            if type(value) is not int:  # pylint: disable=unidiomatic-typecheck
                raise ProtocolError(f"{name} must be an integer")
            if not 0 <= value <= MAX_SEQ:
                raise ProtocolError(f"Invalid {name}")
            return value

        @staticmethod
        def validate_segments(segments: Any) -> None:
            """Check the shape, order, and bounds of planned segment descriptors.

            Parameters
            ----------
            segments : Any
                Untrusted ``segments`` value returned by the snapshot planner or
                loaded from a saved checkpoint.

            Raises
            ------
            ProtocolError
                A descriptor or block range is malformed, unsupported, or out of
                order.

            Notes
            -----
            This checks plan metadata before any segment bytes are requested. The
            package reader validates the sealed segment contents separately.
            """
            if not isinstance(segments, list):
                raise ProtocolError("Invalid snapshot segments")
            previous_index = -1
            for entry in segments:
                if not isinstance(entry, dict):
                    raise ProtocolError("Invalid snapshot segment entry")
                if (
                    not re.fullmatch(r"seg_[0-9a-z]+\.jss", str(entry.get("name", "")))
                    or not re.fullmatch(r"[0-9a-f]{16}", str(entry.get("checksum", "")))
                    or entry.get("mode") not in ("segment", "blocks")
                ):
                    raise ProtocolError("Unsupported snapshot segment descriptor")
                idx = ArchiveValidator.sequence(entry.get("index"), "segment index")
                if idx <= previous_index:
                    raise ProtocolError("Snapshot segments are not strictly ordered")
                previous_index = idx
                min_seq = ArchiveValidator.sequence(entry.get("minSeq"), "minSeq")
                max_seq = ArchiveValidator.sequence(entry.get("maxSeq"), "maxSeq")
                if min_seq > max_seq:
                    raise ProtocolError("Invalid segment sequence bounds")
                if entry["mode"] == "blocks":
                    ranges = entry.get("blocks")
                    if not isinstance(ranges, list) or not ranges:
                        raise ProtocolError("Missing snapshot block ranges")
                    previous = -1
                    for block in ranges:
                        if not isinstance(block, dict):
                            raise ProtocolError("Invalid block range")
                        first = ArchiveValidator.sequence(block.get("first"), "first block")
                        last = ArchiveValidator.sequence(block.get("last"), "last block")
                        if first <= previous or first > last:
                            raise ProtocolError("Invalid or overlapping snapshot block ranges")
                        previous = last


    class BlueskyLakeflowConnect(LakeflowConnect, SupportsPartitionedStream):
        """Read one bounded Jetstream archive refresh through Lakeflow Connect.

        Parameters
        ----------
        config : Options or Mapping[str, Any]
            Validated connector configuration or Lakeflow's string options. A mapping
            is validated at the framework boundary before any archive operation.

        Attributes
        ----------
        config : Options
            Configuration used for planning, filtering, and transport setup.
        _refresh_high : int or None
            Sealed sequence tip pinned for this connector instance.
        _refresh_scope : str or None
            Fingerprint of the configuration pinned for this refresh.

        Notes
        -----
        Create a fresh connector instance for each triggered pipeline refresh.
        """

        def __init__(self, config: Options | Mapping[str, Any]) -> None:
            """Create a connector for one bounded refresh.

            Parameters
            ----------
            config : Options or Mapping[str, Any]
                Validated settings or the string options supplied by Lakeflow.

            Raises
            ------
            TypeError
                ``config`` is neither a validated :class:`Options` instance nor a mapping.

            Notes
            -----
            The first planned window pins a sealed tip and configuration scope for
            this instance. A later triggered refresh should use a new instance.
            """
            if isinstance(config, Mapping):
                config = Options.parse(config, {})
            if not isinstance(config, Options):
                raise TypeError("config must be an Options instance or a mapping")
            super().__init__(config.to_options_dict())
            self.config = config
            self._refresh_high: int | None = None
            self._refresh_scope: str | None = None

        def _config(self, table_name: str, table_options: Mapping[str, Any]) -> Options:
            """Resolve and validate options for the single supported table.

            Parameters
            ----------
            table_name : str
                Table requested by Lakeflow; must be ``events``.
            table_options : Mapping[str, Any]
                Per-table overrides layered onto the connection settings.

            Returns
            -------
            Options
                Validated options for this read.

            Raises
            ------
            ValueError
                The table name or an option is invalid.
            """
            if table_name != "events":
                raise ValueError("Unknown table; supported table: events")
            return self.config.with_table_options(table_options)

        def list_tables(self) -> list[str]:
            """List the tables exposed by this connector.

            Returns
            -------
            list[str]
                The single append-only ``events`` table.
            """
            return ["events"]

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            """Return the Spark schema for decoded archive events.

            Parameters
            ----------
            table_name : str
                Table requested by Lakeflow; must be ``events``.
            table_options : dict[str, str]
                Table options validated against the connector configuration.

            Returns
            -------
            StructType
                Event columns, including JSON record text and optional raw bytes.

            Notes
            -----
            Option validation happens here even though the schema itself is fixed.
            """
            self._config(table_name, table_options)
            return StructType(
                [
                    StructField("seq", LongType(), False),
                    StructField("event_time", TimestampType(), False),
                    StructField("witnessed_at", TimestampType(), False),
                    StructField("did", StringType(), False),
                    StructField("kind", StringType(), False),
                    StructField("operation", StringType(), True),
                    StructField("collection", StringType(), True),
                    StructField("rkey", StringType(), True),
                    StructField("cid", StringType(), True),
                    StructField("rev", StringType(), True),
                    StructField("is_resync", BooleanType(), False),
                    StructField("record", StringType(), True),
                    StructField("event_payload", StringType(), False),
                    StructField("raw_payload", BinaryType(), True),
                ]
            )

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict[str, Any]:
            """Describe the event key, cursor, and append ingestion mode.

            Parameters
            ----------
            table_name : str
                Table requested by Lakeflow; must be ``events``.
            table_options : dict[str, str]
                Table options validated before metadata is returned.

            Returns
            -------
            dict[str, Any]
                Metadata identifying ``seq`` as the key and cursor field.
            """
            self._config(table_name, table_options)
            return {"primary_keys": ["seq"], "cursor_field": "seq", "ingestion_type": "append"}

        @staticmethod
        def _cursor(offset: dict[str, Any] | None, config: Options) -> int:
            """Read a sequence from a checkpoint without changing its scope.

            Parameters
            ----------
            offset : dict[str, Any] or None
                Saved Lakeflow offset, or an empty value on the first read.
            config : Options
                Settings whose fingerprint must match the saved offset.

            Returns
            -------
            int
                Saved sequence, or ``starting_cursor`` for an empty offset.

            Raises
            ------
            ValueError
                The checkpoint version or configuration scope differs.
            ProtocolError
                The saved sequence is invalid.
            """
            if not offset:
                return config.starting_cursor
            if not isinstance(offset, dict) or offset.get("version") != 1:
                raise ValueError("Unsupported checkpoint version")
            if offset.get("scope") != config.fingerprint():
                raise ValueError(
                    "Checkpoint endpoint, start cursor, filters or payload settings changed"
                )
            return ArchiveValidator.sequence(offset.get("seq"), "checkpoint seq")

        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict[str, Any] | None = None,
        ) -> dict[str, Any]:
            """Plan one bounded archive window and return its candidate offset.

            Parameters
            ----------
            table_name : str
                Table requested by Lakeflow; must be ``events``.
            table_options : dict[str, str]
                Per-table filters and read limits.
            start_offset : dict[str, Any] or None, optional
                Last committed offset. An empty value starts at ``starting_cursor``.

            Returns
            -------
            dict[str, Any]
                Candidate offset containing the end sequence and serialized plan,
                or the original empty/committed offset when no progress is possible.

            Raises
            ------
            CursorTooOld
                The archive tip is behind the committed checkpoint.
            ProtocolError
                Planner pages are inconsistent, too large, or make no progress.

            Notes
            -----
            The first planner response pins the sealed tip for this instance.
            Subsequent pages must reach that tip without extending the window.
            Returning an offset does not commit it; Spark commits after the batch.
            """
            config = self._config(table_name, table_options)
            after = self._cursor(start_offset, config)
            scope = config.fingerprint()
            if self._refresh_scope is not None and self._refresh_scope != scope:
                raise ValueError("A connector instance cannot change its scope during a refresh")
            self._refresh_scope = scope
            if self._refresh_high is not None and after >= self._refresh_high:
                return start_offset or {}
            # A sequence window bounds the number of rows even before exact filtering.
            before = self._refresh_high or min(after + config.max_events_per_refresh, MAX_SEQ)
            if before == after:
                return start_offset or {}
            pages = []
            through = after
            with pinned_transport(config) as transport:
                for _ in range(MAX_PLAN_PAGES):
                    page = transport.plan(through, before)
                    tip = ArchiveValidator.sequence(page.get("sealedTipSeq"), "sealedTipSeq")
                    covered = ArchiveValidator.sequence(
                        page.get("plannedThroughSeq"), "plannedThroughSeq"
                    )
                    if tip < after:
                        raise CursorTooOld("Archive tip is behind checkpoint; endpoint may have reset")
                    if tip > before or covered > tip or covered < through:
                        raise ProtocolError("Snapshot planner returned inconsistent sequence bounds")
                    if self._refresh_high is None:
                        self._refresh_high = tip
                    if tip != self._refresh_high:
                        raise ProtocolError("Pinned archive tip changed during planning")
                    before = tip
                    ArchiveValidator.validate_segments(page.get("segments"))
                    pages.append({"after": through, "through": covered, "segments": page["segments"]})
                    if len(json.dumps(pages)) > MAX_PLAN_BYTES:
                        raise ProtocolError("Snapshot plan too large; reduce max_events_per_refresh")
                    if covered == tip:
                        break
                    if covered == through:
                        raise ProtocolError("Snapshot planner made no progress")
                    through = covered
                else:
                    raise ProtocolError("Snapshot planning exceeded the page limit")
            if before == after:
                return start_offset or {}
            return {
                "version": 1,
                "scope": scope,
                "seq": before,
                "after": after,
                "plan": json.dumps(pages, separators=(",", ":")),
            }

        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict[str, Any] | None = None,
            end_offset: dict[str, Any] | None = None,
        ) -> list[dict[str, Any]]:
            """Create the single ordered partition for a recorded plan.

            Parameters
            ----------
            table_name : str
                Table requested by Lakeflow; must be ``events``.
            table_options : dict[str, str]
                Settings used to validate both offsets.
            start_offset : dict[str, Any] or None, optional
                Last committed offset.
            end_offset : dict[str, Any] or None, optional
                Planned candidate offset. If absent, a new window is planned.

            Returns
            -------
            list[dict[str, Any]]
                One partition carrying the saved end offset, or an empty list when
                the window contains no new sequence positions.

            Raises
            ------
            ValueError
                The offsets do not describe the same recorded window.

            Notes
            -----
            Partitioning provides Spark replay semantics here, not parallel reads.
            """
            config = self._config(table_name, table_options)
            if end_offset is None:
                end_offset = self.latest_offset(table_name, table_options, start_offset)
            after = self._cursor(start_offset, config)
            through = self._cursor(end_offset, config)
            if through == after:
                return []
            if through < after or end_offset.get("after") != after:
                raise ValueError("Checkpoint range does not match the recorded plan")
            # A single partition keeps ordering and a single overall read time budget.
            # The mixin is used for replay correctness, not parallelism in this version.
            return [{"start": after, "end": end_offset}]

        def read_partition(
            self,
            table_name: str,
            partition: dict[str, Any],
            table_options: dict[str, str],
        ) -> Iterator[dict[str, Any]]:
            """Read exactly the segments pinned in a Lakeflow partition.

            Parameters
            ----------
            table_name : str
                Table requested by Lakeflow; must be ``events``.
            partition : dict[str, Any]
                Start sequence and candidate end offset containing the saved plan.
            table_options : dict[str, str]
                Settings used to validate scope and apply exact event filters.

            Yields
            ------
            dict[str, Any]
                Matching event rows in increasing sequence order.

            Raises
            ------
            ProtocolError
                The saved plan is discontinuous, malformed, or produces unordered
                events.

            Notes
            -----
            This method never calls the planner. A Spark retry reads the same
            checksum of archive generation or fails if that generation is gone.
            """
            config = self._config(table_name, table_options)
            if not isinstance(partition, dict) or not isinstance(partition.get("end"), dict):
                raise ProtocolError("Invalid partition")
            end = partition["end"]
            after = ArchiveValidator.sequence(partition.get("start"), "partition start")
            through = self._cursor(end, config)
            if (
                ArchiveValidator.sequence(end.get("after"), "checkpoint after") != after
                or after >= through
            ):
                raise ProtocolError("Invalid partition range")
            if not isinstance(end.get("plan"), str) or len(end["plan"]) > MAX_PLAN_BYTES:
                raise ProtocolError("Invalid checkpoint plan")
            try:
                pages = json.loads(end["plan"])
            except ValueError:
                raise ProtocolError("Invalid checkpoint plan") from None
            if not isinstance(pages, list) or not pages or len(pages) > MAX_PLAN_PAGES:
                raise ProtocolError("Invalid checkpoint pages")
            covered = after
            previous = after
            with pinned_transport(config) as transport:
                for page in pages:
                    if not isinstance(page, dict):
                        raise ProtocolError("Invalid checkpoint page")
                    page_after = ArchiveValidator.sequence(page.get("after"), "page after")
                    page_through = ArchiveValidator.sequence(page.get("through"), "page through")
                    if page_after != covered or not covered < page_through <= through:
                        raise ProtocolError("Discontinuous checkpoint plan")
                    segments = page.get("segments")
                    ArchiveValidator.validate_segments(segments)
                    for entry in segments:
                        for event in pinned_rows(
                            transport, entry, covered, page_through, config.include_raw_payload
                        ):
                            if event["seq"] <= previous:
                                raise ProtocolError("Overlapping or out-of-order archive events")
                            previous = event["seq"]
                            if config.matches(event):
                                yield event
                    covered = page_through
                if covered != through:
                    raise ProtocolError("Incomplete checkpoint plan")

        def read_table(
            self,
            table_name: str,
            start_offset: dict[str, Any] | None,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict[str, Any]], dict[str, Any]]:
            """Complete a bounded read for Lakeflow's direct reader interface.

            Parameters
            ----------
            table_name : str
                Table requested by Lakeflow; must be ``events``.
            start_offset : dict[str, Any] or None
                Last committed offset, or an empty value for the first read.
            table_options : dict[str, str]
                Per-table filters and read limits.

            Returns
            -------
            tuple[Iterator[dict[str, Any]], dict[str, Any]]
                Iterator over fully materialized rows and their candidate end
                offset. The caller must commit that offset only after writing rows.

            Raises
            ------
            ProtocolError
                The materialized batch exceeds the memory budget or archive
                validation fails.

            Notes
            -----
            All archive I/O finishes before this method returns. The partitioned
            Spark path instead streams rows from :meth:`read_partition`.
            """
            end = self.latest_offset(table_name, table_options, start_offset)
            # Complete bounded I/O before returning a candidate offset. Only Lakeflow/Spark
            # may commit it, after consuming rows and successfully writing the Delta batch.
            rows = []
            size = 0
            for partition in self.get_partitions(table_name, table_options, start_offset, end):
                for row in self.read_partition(table_name, partition, table_options):
                    size += len(json.dumps(row).encode())
                    if size > MAX_BATCH_BYTES:
                        raise ProtocolError(
                            "Batch exceeds memory budget; reduce max_events_per_refresh"
                        )
                    rows.append(row)
            return iter(rows), end


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = BlueskyLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
